#!/usr/bin/env bash
# One-command, GPU-free reproduction of every RQ1-RQ4 LaTeX table in the paper.
#
# Reads the shipped, already-aggregated per-cell/per-setting CSV and JSON files under outputs/
# (a few MB) that scripts/paper_latex_tables.py was built to read. No GPU, no training, seconds
# to run.
#
# Usage:
#   uv sync
#   bash scripts/reproduce_tables.sh
#
# Output: note/tables/{rq1,rq2,rq3,rq4}.tex (also printed to stdout).
#
# Optional, not run by default: outputs/ALL_RQ_DATA.csv (one of paper_latex_tables.py's inputs)
# can itself be regenerated from the shipped raw per-sample prediction trees
# (outputs/patch_ablation/), rather than trusted as shipped, via:
#   uv run python scripts/all_rq_data.py
# The other intermediate CSVs it reads (outputs/p1_regression/, outputs/gate_lambda_sweep/,
# outputs/m1_correction_direction/, outputs/rq1_alignment/, outputs/gate_transplant/, ...) are
# each regenerated by their own scripts/analysis_*.py / scripts/gate_*.py script from the shipped
# outputs/sample_frame.csv.gz-style per-sample dumps; see README.md "Known limitations" -- some
# of those per-sample dumps are large and only a subset is shipped here, so re-deriving every
# intermediate CSV end-to-end is not guaranteed to reproduce bit-for-bit and is not part of this
# one-command path. This script only re-runs the step that is fully self-contained
# (all_rq_data.py) plus the final render.
set -euo pipefail
cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUN="${RUN:-uv run python}"

echo "[1/1] rendering paper LaTeX tables from the shipped outputs/*.csv, *.json ..."
$RUN scripts/paper_latex_tables.py --outdir note/tables

echo
echo "Done. note/tables/{rq1,rq2,rq3,rq4}.tex regenerated."
echo
echo "Note: outputs/ALL_RQ_DATA.csv above is used AS SHIPPED, not re-derived. scripts/all_rq_data.py"
echo "(and the raw per-sample prediction trees it reads, e.g. outputs/patch_ablation/) are NOT part"
echo "of this repository -- see README.md 'Known limitations'. If you have those raw trees"
echo "separately, 'uv run python scripts/all_rq_data.py' will regenerate ALL_RQ_DATA.csv from them."
